### ISSUE TITLE
Merging calorie tracking features

### ISSUE THREAD

**Issue by Indomet** [Indomet/WioPlay#12]
In GitLab by @joelmat on Apr 11, 2023, 15:03

# Requirement

As a user, I want to the system to track my workout progress by establishing a connection between the terminal and app, such that I can use a feature unified app to achieve my goals

[Related to: #9 #10 #3 #4 #6]

## Acceptance criteria

- [x] the user interface for the calorie tracking feature should be intuitive
- [x] the user interface for the calorie tracking feature should be user-friendly
- [x] The terminal should send calories burnt data to the app
- [x] The app should indicate to the terminal that a workout has started
